services:
  adminer:
    image: adminer:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN}`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=le"
      - "traefik.http.routers.adminer.middlewares=adminer-auth"
      - "traefik.http.middlewares.adminer-auth.basicauth.users=${ADMINER_BASICAUTH}"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
